package io.secureai.backend.domain.report.service;

import io.secureai.backend.domain.analysis.entity.AnalysisSession;
import io.secureai.backend.domain.analysis.entity.Vulnerability;
import io.secureai.backend.domain.project.entity.Project;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Slf4j
@Component
public class HtmlReportGenerator {

    private static final DateTimeFormatter FORMATTER =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

    public String generate(List<Vulnerability> vulns, Project project, AnalysisSession session) {
        Map<String, Long> bySeverity = vulns.stream()
                .collect(Collectors.groupingBy(
                        v -> v.getSeverity().toUpperCase(), Collectors.counting()));

        long critical = bySeverity.getOrDefault("CRITICAL", 0L);
        long high     = bySeverity.getOrDefault("HIGH", 0L);
        long medium   = bySeverity.getOrDefault("MEDIUM", 0L);
        long low      = bySeverity.getOrDefault("LOW", 0L);

        return """
                <!DOCTYPE html>
                <html lang="ko">
                <head>
                <meta charset="UTF-8"/>
                <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
                <title>SecureAI 보안 분석 리포트 — %s</title>
                <style>
                  *{box-sizing:border-box;margin:0;padding:0}
                  body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;
                       background:#0f0f11;color:#e5e7eb;padding:40px 60px;line-height:1.6}
                  h1{font-size:26px;font-weight:800;color:#fff;margin-bottom:4px}
                  h2{font-size:16px;font-weight:700;color:#f9fafb;margin:32px 0 12px}
                  .meta{font-size:12px;color:#6b7280;margin-bottom:36px}
                  .chips{display:flex;gap:10px;margin-bottom:32px}
                  .chip{padding:8px 18px;border-radius:8px;font-size:13px;font-weight:700}
                  .critical{background:#450a0a;color:#fca5a5}
                  .high{background:#431407;color:#fdba74}
                  .medium{background:#422006;color:#fcd34d}
                  .low{background:#052e16;color:#86efac}
                  table{width:100%%;border-collapse:collapse;font-size:13px;margin-bottom:40px}
                  th{background:#1f2937;color:#9ca3af;font-weight:600;
                     padding:10px 14px;text-align:left;border-bottom:1px solid #374151}
                  td{padding:10px 14px;border-bottom:1px solid #1f2937;vertical-align:top}
                  tr:hover td{background:#111827}
                  .sev{font-weight:700;font-size:11px;padding:2px 8px;border-radius:4px}
                  .footer{font-size:11px;color:#4b5563;text-align:center;margin-top:60px}
                </style>
                </head>
                <body>
                <h1>SecureAI 보안 분석 리포트</h1>
                <div class="meta">
                  프로젝트: %s &nbsp;·&nbsp; 생성 일시: %s%s
                </div>
                <div class="chips">
                  <div class="chip critical">CRITICAL %d</div>
                  <div class="chip high">HIGH %d</div>
                  <div class="chip medium">MEDIUM %d</div>
                  <div class="chip low">LOW %d</div>
                </div>
                <h2>취약점 목록 (%d건)</h2>
                <table>
                  <thead>
                    <tr>
                      <th>심각도</th><th>유형</th><th>파일 경로</th>
                      <th>줄 번호</th><th>CWE</th><th>OWASP</th><th>상태</th>
                    </tr>
                  </thead>
                  <tbody>
                %s
                  </tbody>
                </table>
                <div class="footer">Generated by SecureAI Engine</div>
                </body>
                </html>
                """.formatted(
                escapeHtml(project.getName()),
                escapeHtml(project.getName()),
                OffsetDateTime.now().format(FORMATTER),
                session != null ? " &nbsp;·&nbsp; 세션 ID: " + session.getId() : "",
                critical, high, medium, low,
                vulns.size(),
                buildRows(vulns)
        );
    }

    private String buildRows(List<Vulnerability> vulns) {
        if (vulns.isEmpty()) {
            return "<tr><td colspan=\"7\" style=\"text-align:center;color:#6b7280\">취약점 없음</td></tr>";
        }
        StringBuilder sb = new StringBuilder();
        for (Vulnerability v : vulns) {
            String sev = v.getSeverity().toUpperCase();
            sb.append("    <tr>")
              .append("<td><span class=\"sev ").append(sev.toLowerCase()).append("\">").append(sev).append("</span></td>")
              .append("<td>").append(escapeHtml(v.getVulnType())).append("</td>")
              .append("<td style=\"font-family:monospace;font-size:12px\">").append(escapeHtml(v.getFilePath())).append("</td>")
              .append("<td>").append(v.getLineNumber() != null ? v.getLineNumber() : "—").append("</td>")
              .append("<td>").append(v.getCwe() != null ? escapeHtml(v.getCwe()) : "—").append("</td>")
              .append("<td>").append(v.getOwasp() != null ? escapeHtml(v.getOwasp()) : "—").append("</td>")
              .append("<td>").append(escapeHtml(v.getStatus())).append("</td>")
              .append("</tr>\n");
        }
        return sb.toString();
    }

    private String escapeHtml(String s) {
        if (s == null) return "";
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                .replace("\"", "&quot;").replace("'", "&#39;");
    }
}
