package io.secureai.backend.domain.report.service;

import io.secureai.backend.domain.analysis.entity.AnalysisSession;
import io.secureai.backend.domain.analysis.entity.Vulnerability;
import io.secureai.backend.domain.project.entity.Project;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Slf4j
@Component
public class MarkdownReportGenerator {

    private static final DateTimeFormatter FORMATTER =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

    public String generate(List<Vulnerability> vulns, Project project, AnalysisSession session) {
        Map<String, Long> bySeverity = vulns.stream()
                .collect(Collectors.groupingBy(
                        v -> v.getSeverity().toUpperCase(), Collectors.counting()));

        long critical = bySeverity.getOrDefault("CRITICAL", 0L);
        long high     = bySeverity.getOrDefault("HIGH", 0L);
        long medium   = bySeverity.getOrDefault("MEDIUM", 0L);
        long low      = bySeverity.getOrDefault("LOW", 0L);

        StringBuilder sb = new StringBuilder();

        sb.append("# SecureAI 보안 분석 리포트\n\n");
        sb.append("- **프로젝트**: ").append(project.getName()).append("\n");
        sb.append("- **생성 일시**: ").append(OffsetDateTime.now().format(FORMATTER)).append("\n");
        if (session != null) {
            sb.append("- **세션 ID**: ").append(session.getId()).append("\n");
        }
        sb.append("\n---\n\n");

        sb.append("## 심각도 요약\n\n");
        sb.append("| 심각도 | 건수 |\n");
        sb.append("|--------|------|\n");
        sb.append("| 🔴 CRITICAL | ").append(critical).append(" |\n");
        sb.append("| 🟠 HIGH     | ").append(high).append(" |\n");
        sb.append("| 🟡 MEDIUM   | ").append(medium).append(" |\n");
        sb.append("| 🟢 LOW      | ").append(low).append(" |\n");
        sb.append("| **합계**    | **").append(vulns.size()).append("** |\n\n");

        sb.append("---\n\n");
        sb.append("## 취약점 목록\n\n");

        if (vulns.isEmpty()) {
            sb.append("취약점이 없습니다.\n");
        } else {
            sb.append("| 심각도 | 유형 | 파일 경로 | 줄 번호 | CWE | OWASP | 상태 |\n");
            sb.append("|--------|------|-----------|---------|-----|-------|------|\n");
            for (Vulnerability v : vulns) {
                sb.append("| ").append(escapeMd(v.getSeverity().toUpperCase()))
                  .append(" | ").append(escapeMd(v.getVulnType()))
                  .append(" | `").append(escapeMd(v.getFilePath())).append("`")
                  .append(" | ").append(v.getLineNumber() != null ? v.getLineNumber() : "—")
                  .append(" | ").append(v.getCwe() != null ? escapeMd(v.getCwe()) : "—")
                  .append(" | ").append(v.getOwasp() != null ? escapeMd(v.getOwasp()) : "—")
                  .append(" | ").append(escapeMd(v.getStatus()))
                  .append(" |\n");
            }
        }

        sb.append("\n---\n\n");
        sb.append("*Generated by SecureAI Engine*\n");

        return sb.toString();
    }

    private String escapeMd(String s) {
        if (s == null) return "";
        return s.replace("|", "\\|").replace("`", "'");
    }
}
